includes:
    #TODO: Rename this file. These functions are what enables single use nodes in nodepool.
  - python-file: openstack_functions.py

pipelines:
  - name: check
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: "Build failed.  To recheck use 'xenserver: recheck'.  For 3rd party ci contact info: https://wiki.openstack.org/wiki/ThirdPartySystems"
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        # TODO: Change "myvendor" below to your vendor's name to add a custom
        # recheck trigger that runs the check pipeline jobs when someone
        # adds a comment to a review that says "recheck myvendor".
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*xenserver:*\s*recheck\s*$

    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
      smtp:
        to: jianghua.wang@citrix.com
        from: jianghua.wang@citrix.com
        subject: Citrix XenServer CI failure - Upstream change {change}
    merge-failure:
      gerrit:
        verified: -1
      smtp:
        to: jianghua.wang@citrix.com
        from: jianghua.wang@citrix.com
        subject: Upstream change {change} has a merge failure
    ignore-dependencies: False


  - name: check-fuel-plugin-xenserver
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: "Build failed.  To recheck use 'xenserver: recheck'.  For 3rd party ci contact info: https://wiki.openstack.org/wiki/ThirdPartySystems"
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*xenserver:*\s*recheck\s*$
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
      smtp:
        to: jianghua.wang@citrix.com
        from: jianghua.wang@citrix.com
        subject: Citrix XenServer CI failure - Upstream change {change}
    merge-failure:
      gerrit:
        verified: -1
      smtp:
        to: jianghua.wang@citrix.com
        from: jianghua.wang@citrix.com
        subject: Upstream change {change} has a merge failure
    ignore-dependencies: False


  - name: check-coverage
    description: Newly uploaded patchsets enter this pipeline to receive an initial +/-1 Verified vote from Jenkins.
    failure-message: "Build failed.  To recheck use 'xenserver: recheck'.  For 3rd party ci contact info: https://wiki.openstack.org/wiki/ThirdPartySystems"
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*xenserver:*\s*recheck\s*$
    success:
      gerrit:
        verified: 1
    failure:
      gerrit:
        verified: -1
      smtp:
        to: jianghua.wang@citrix.com
        from: jianghua.wang@citrix.com
        subject: Citrix XenServer CI failure - Upstream change {change}
    merge-failure:
      gerrit:
        verified: -1
      smtp:
        to: jianghua.wang@citrix.com
        from: jianghua.wang@citrix.com
        subject: Upstream change {change} has a merge failure
    ignore-dependencies: False


  - name: silent
    description: Newly uploaded patchsets enter this pipeline to check jobs whose results are NOT to be posted (because e.g. they are not yet stable)
    manager: IndependentPipelineManager
    trigger:
      gerrit:
        - event: patchset-created
        - event: change-restored
        - event: comment-added
          comment: (?i)^(Patch Set [0-9]+:)?( [\w\\+-]*)*(\n\n)?\s*xenserver:*\s*recheck\s*$
    success:
      smtp:
        to: jianghua.wang@citrix.com
        from: zuul@zuul.openstack.xenproject.org
        subject: 'Silent check of {change.project} {change.number},{change.patchset} passed'
    failure:
      smtp:
        to: jianghua.wang@citrix.com
        from: zuul@zuul.openstack.xenproject.org
        subject: 'Silent check of {change.project} {change.number},{change.patchset} failed'
    ignore-dependencies: False


jobs:
  - name: ^dsvm-tempest.*$
    skip-if:
      - project: ^openstack/nova$
        all-files-match-any:
          - ^.*\.rst$
          - ^doc/.*$
          - ^nova/tests/.*$
          - ^nova/virt/baremetal/.*$
          - ^nova/virt/hyperv/.*$
          - ^nova/virt/ironic/.*$
          - ^nova/virt/vmwareapi/.*$
          - ^nova/virt/libvirt/.*$
          - ^tools/.*$
          - ^tox.ini$
      - project: ^openstack/neutron$
        all-files-match-any:
          - ^.*\.rst$
          - ^doc/.*$
          - ^neutron/locale/.*$
          - ^neutron/tests/.*$
          - ^releasenotes/.*$
          - ^tools/.*$
          - ^tox.ini$
    parameter-function: single_use_node

  - name: dsvm-tempest-nova-network
    branch: ^stable\/[a-n].*$
    voting: true

  - name: ^dsvm-tempest-neutron-network.*$
    branch: ^master.*$
    voting: true

  - name: check-coverage
    files:
      - ^nova/virt/xenapi/.*$
      - ^os_xenapi/.*$
    branch: ^master.*$
    voting: false

  - name: test-vgpu
    files:
      - ^nova/virt/xenapi/.*$
      - ^nova/compute/.*$
      - ^nova/scheduler/.*$
      - ^nova/api/openstack/placement/.*$
      - ^os_xenapi/client/.*$
      - ^os_xenapi/dom0/.*$
    branch: ^master.*$
    voting: false

projects:
  #- name: openstack-dev/sandbox
  #  silent:
  #    - dsvm-tempest-nova-network
  #    - dsvm-tempest-neutron-network

  - name: citrix-openstack/devstack-gate
    check:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network

  - name: openstack/fuel-plugin-xenserver
    check-fuel-plugin-xenserver:
      - check-fuel-xenserver-plugin-ely
      - check-fuel-xenserver-plugin
      - check-fuel-xenserver-6.5-plugin

  - name: openstack/nova
    check:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network
      - test-vgpu
    silent:
      ##- dsvm-tempest-neutron-network-internal
      - check-coverage

  - name: openstack/neutron
    check:
      - dsvm-tempest-neutron-network
    #silent:
      #- dsvm-tempest-neutron-network-internal

  - name: openstack/os-xenapi
    check:
      - dsvm-tempest-neutron-network
      - test-vgpu
    check-coverage:
      - check-coverage

  - name: openstack/tempest
    check:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network
    #silent:
      #- dsvm-tempest-neutron-network-internal

  - name: openstack-dev/devstack
    check:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network
    #silent:
      #- dsvm-tempest-neutron-network-internal

  - name: openstack/xenapi-os-testing
    check:
      - dsvm-tempest-nova-network
      - dsvm-tempest-neutron-network
    #silent:
    #  - dsvm-tempest-neutron-network-internal

  # Start for Other pojects #
